FEA: Post Round Menu
TTTReborn/ttt-reborn pull request #34
Opened 2021-06-18 05:14 UTC by mzegar

2021-06-18 08:57 UTC, Westsaid requested changes
Just small design thoughts

2021-06-18 08:57 UTC, Westsaid commented on code/ui/PostRoundMenu.scss
> +        display: none;
Why not opacity:0... this is better in most cases because you can set transitions on opacity but not display:none

2021-06-18 08:57 UTC, Westsaid commented on code/rounds/InProgressRound.cs
> +            TTTPlayer.ClientOpenAndSetPostRoundMenu(winningRole.Name);
Why just the Name? Couldn't we also pass the winningRole.Color to set it as background-color for the Header

2021-06-18 08:57 UTC, Westsaid commented on code/ui/PostRoundMenu.scss
> +
If we set the BG color, we should also have a `margin:15px 0;`.

2021-06-19 07:37 UTC, Alf21 approved these changes

2021-06-19 10:17 UTC, Westsaid commented
Good that we can access the Color of the winning team now. I don't really like that the text is colored that way:
![image](https://user-images.githubusercontent.com/58175915/122638623-72694a80-d0f5-11eb-96cf-2b3d2e74c64f.png)

Its a little hard to read, I would prefer to make it more like a banner: Set the BG color to the winning role. That would look like that:
![image](https://user-images.githubusercontent.com/58175915/122638964-9a59ad80-d0f7-11eb-81c4-2c32c7496045.png)
The contrast ratio is more sufficient here.

2021-06-19 10:24 UTC, Westsaid approved these changes

2021-06-19 10:29 UTC, merged